CREATE DATABASE IF NOT EXISTS CategoriaDB;
CREATE DATABASE IF NOT EXISTS DirectorDB;
CREATE DATABASE IF NOT EXISTS IdiomaDB;
CREATE DATABASE IF NOT EXISTS PeliculasDB;
CREATE DATABASE IF NOT EXISTS resenias_db;
CREATE DATABASE IF NOT EXISTS UsuariosDB;
CREATE DATABASE IF NOT EXISTS RecomendacionDB;
CREATE DATABASE IF NOT EXISTS NotificacionDB;