spring.application.name=usuario
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/UsuarioDB}
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
pelicula.service.url=${PELICULA_SERVICE_URL:http://localhost:8083}