spring.application.name=recomendacion

spring.datasource.url=jdbc:mysql://mysql-db:3306/RecomendacionDB
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086

pelicula.service.username=admin
pelicula.service.password=1234